version: '2'

services:
  development:
    image: malera/ndconf
    hostname: "dev"
    working_dir: /conf/src
    volumes:
      - $HOME/.ssh:/conf/.ssh:ro
      - $HOME/.gitconfig:/conf/.gitconfig
      - ./:/conf/src:rw
    environment:
      - NODE_ENV=development
