version: '3.4'

services:
  dev:
    build: ./docker
    image: nd-conf
    hostname: "dev"
    working_dir: /home/node/nd-conf
    volumes:
      - $PWD:/home/node/nd-conf
      - $HOME/.ssh:/home/node/.ssh
      - $HOME/.gitconfig:/home/node/.gitconfig
    environment:
      - NODE_ENV=development
