version: '2'

services:
  dev:
    #build: ./docker
    image: malera/nd-conf
    hostname: "dev"
    working_dir: /conf/src
    volumes:
      - $HOME/.ssh:/conf/.ssh:ro
      - $HOME/.gitconfig:/conf/.gitconfig:ro
      - ./:/conf/src:rw
    environment:
      - NODE_ENV=development
